"""Tab 10 / Method And Honesty. Build Spec Section 07.

    Exactly what is real, exactly what is seeded, exactly what is
    simplified.

This tab is a scoring instrument. In a project about accountability, a
rigorous self-audit is worth more than another feature, and it pre-empts
the sharpest objection a judge can raise, which is that the detector finds
imitations the builder generated.

REUSE
    The contents of this tab become the honesty section of the write-up
    almost verbatim. Written once, carefully, and used twice.
"""

from __future__ import annotations

import pandas as pd
import streamlit as st

import components as C
import data

REAL_VERSUS_SIMPLIFIED = [
    ("Organisation corpus",
     "IRS Business Master File, unmodified",
     "Nothing"),
    ("Standing information",
     "IRS Auto-Revocation List, which records failure to file, "
     "not wrongdoing",
     "Nothing"),
    ("Activity and location data",
     "IATI Datastore slice",
     "Coordinates jittered where precision would be identifying"),
    ("Imitating organisations",
     "Nothing",
     "All of them, generated by tools/make_synthetic.py, "
     "batch SYNTH_ADVERSARY_V1"),
    ("Beneficiary records",
     "Nothing",
     "Entirely synthetic. Handling real beneficiary data here would be "
     "unethical."),
    ("Attrition rates",
     "Calibrated against published WFP truck figures",
     "Individual delivery events are modelled"),
    ("On-chain receipts",
     "Genuinely minted and independently verifiable",
     "Solana devnet, not mainnet"),
    ("Privacy guarantee",
     "A real Snowflake privacy policy with real noise and a real budget",
     "Epsilon tuned for demonstration legibility rather than production"),
]

LIMITATIONS = [
    "It cannot prove intent. A high similarity score is a reason to look "
    "closer, never a verdict about a person.",
    "It cannot detect an imitator whose name shares no meaning with its "
    "target. Detection by meaning has a blind spot for names chosen at "
    "random.",
    "It cannot see money that never entered a reporting system at all, "
    "which is very likely where the largest losses actually sit.",
    "A receipt proves a claim was recorded at a point in time. It does not "
    "prove goods reached a person. Anyone who tells you a blockchain solves "
    "that is selling something.",
]

FEATURES = [
    ("Privacy policy, differential privacy", "Tab 05, The Wall", "new to me"),
    ("AI_EMBED and VECTOR_COSINE_SIMILARITY", "Tabs 01 and 02", "new to me"),
    ("AI_FILTER as a semantic predicate", "Tab 01, confirmation chip", "new to me"),
    ("H3 grid functions and ST_DISTANCE", "Tabs 03 and 04", "used before"),
    ("SQL UDF, decomposable score", "Tab 01, waterfall", "used before"),
    ("Dynamic Tables with TARGET_LAG", "Tab 00, pipeline strip", "used before"),
    ("Semantic view", "Tab 08, Ask The Warehouse", "new to me"),
    ("Time Travel", "Tab 07, The Historian", "used before"),
]

SQL_FILES = [
    ("00_account_setup.sql", "warehouse, database, schemas, edition assert"),
    ("01_raw_tables.sql", "landing and staging schema"),
    ("02_load_bmf.sql", "IRS Business Master File and revocation list"),
    ("03_load_iati.sql", "IATI activity and location data"),
    ("04_seed_adversaries.sql", "synthetic clones, labelled, plus the citations"),
    ("05_staging_dynamic_tables.sql", "six Dynamic Tables at 60 second lag"),
    ("06_embeddings.sql", "AI_EMBED batch, run once"),
    ("07_clone_detection.sql", "vector similarity and the evasion gap"),
    ("08_geospatial_h3.sql", "H3 geometry and hex risk"),
    ("09_risk_score_udf.sql", "the decomposable score"),
    ("10_semantic_view.sql", "semantic layer"),
    ("11_privacy_policy.sql", "differential privacy, run first in practice"),
    ("12_serving_views.sql", "terminal serving views"),
    ("13_oracle_queue.sql", "mint queue and mint log"),
    ("99_acceptance_checks.sql", "the gate"),
]


def render() -> None:
    C.tab_title(
        "Method And Honesty",
        "Exactly what is real, exactly what is seeded, exactly what is "
        "simplified.",
    )

    totals = data.run("Q_HONESTY_TOTALS")
    real_rows = int(totals.iloc[0]["real_rows"] or 0) if len(totals) else 0
    seeded_rows = int(totals.iloc[0]["seeded_rows"] or 0) if len(totals) else 0

    # ---------------------------------------------------------------- S1
    C.hero(
        f"{real_rows:,} real · {seeded_rows:,} seeded",
        "every seeded row is labelled in the data, not only in the interface",
    )

    # ---------------------------------------------------------------- S2
    C.section("Provenance, counted live")
    provenance = data.run("Q_PROVENANCE")
    if provenance.empty:
        st.markdown('<div class="gp-source">No provenance rows.</div>',
                    unsafe_allow_html=True)
    else:
        table = provenance.copy()
        table.columns = [c.lower() for c in table.columns]
        table["source"] = table["batch_id"].map({
            "IRS_BMF_2026": "public IRS filings",
            "IATI_2026": "IATI datastore",
            "SYNTH_ADVERSARY_V1": "tools/make_synthetic.py",
            "SOLANA_DEVNET": "solana devnet, via the bridge",
        }).fillna("unclassified")
        st.dataframe(
            table[["table_name", "batch_id", "rows", "source"]],
            use_container_width=True, hide_index=True,
        )
    corpus = data.run("Q_CORPUS_NOTE")
    note = (
        "Counted live from the tables themselves, so this claim cannot drift "
        "from reality. If the generator produced more rows tomorrow, this "
        "table would say so without anybody editing it."
    )
    if len(corpus):
        loaded = int(corpus.iloc[0]["rows_loaded"] or 0)
        available = int(corpus.iloc[0]["rows_available"] or 0)
        if available > loaded:
            note += (
                f" The IRS Business Master File extracts used here contain "
                f"{available:,} organisations with a resolvable coordinate. "
                f"{loaded:,} of them carry an embedding, weighted toward the "
                "causes an impersonator actually targets, because embedding "
                "the full corpus is neither necessary for the detection nor "
                "affordable on a trial warehouse. Every figure above counts "
                "rows that are actually loaded, never rows that merely exist "
                "upstream."
            )
    C.source_note(note)

    # ---------------------------------------------------------------- S3
    C.section("Real versus simplified")
    st.dataframe(
        pd.DataFrame(REAL_VERSUS_SIMPLIFIED,
                     columns=["element", "real", "seeded or simplified"]),
        use_container_width=True, hide_index=True,
    )

    # ---------------------------------------------------------------- S4
    C.section("What this cannot do")
    for item in LIMITATIONS:
        st.markdown(
            f'<div style="border-left:3px solid #E4E7EB;padding:8px 0 8px 14px;'
            f'margin-bottom:10px;font-size:14px;line-height:1.6">{item}</div>',
            unsafe_allow_html=True,
        )

    # ------------------------------------------------------------ S5, S6
    fcol, rcol = st.columns(2, gap="medium")

    with fcol:
        C.section("Snowflake features used")
        st.dataframe(
            pd.DataFrame(FEATURES, columns=["feature", "where", "new to me?"]),
            use_container_width=True, hide_index=True,
        )

    with rcol:
        C.section("Reproduce it")
        st.markdown(
            "\n".join(
                f"{i}. **{name}** — {note}"
                for i, (name, note) in enumerate(SQL_FILES, start=1)
            )
        )
        C.source_note(
            "Run in that order against an Enterprise Edition account. "
            "11_privacy_policy.sql is numbered where it sits in the dependency "
            "graph but is built first in practice, because it is the only "
            "component that can fail in a way that cannot be fixed later."
        )

    # Acceptance checks, if the warehouse can answer them.
    if not data.is_preview():
        C.section("Acceptance checks")
        try:
            checks = data.run("Q_ACCEPTANCE")
            st.dataframe(checks, use_container_width=True, hide_index=True)
            failed = int((checks["result"] == "FAIL").sum())
            st.markdown(
                C.chip("build accepted" if failed == 0
                       else f"{failed} checks failing",
                       "confirmed" if failed == 0 else "flagged"),
                unsafe_allow_html=True,
            )
        except Exception as exc:              # noqa: BLE001
            st.markdown(f'<div class="gp-source">Acceptance view not '
                        f'available: {exc}</div>', unsafe_allow_html=True)

    # ---------------------------------------------------------------- S7
    C.section("Ethics")
    st.markdown(
        """
Two decisions in this build were made on ethical grounds rather than
technical ones, and both cost something.

**No real beneficiary data was used, at any point.** Not anonymised, not
aggregated, not with permission. The beneficiary layer is entirely
synthetic. This weakens the demonstration, because a privacy guarantee
over fabricated people is a guarantee over nobody, and it is still the
right call: the correct way to handle a dataset of aid recipients in a
weekend project is not to have one. The privacy policy, the noise and the
budget on The Wall are all real Snowflake features doing real work; the
people they protect are not real, and that is stated on the tab itself.

**Devnet, not mainnet.** A public ledger is permanent. Writing receipts
about aid delivery to a permanent public chain is a decision that deserves
more scrutiny than a hackathon weekend allows, so this build writes to a
test network and says so everywhere it appears. The receipts are genuinely
minted and independently verifiable, and they are on devnet.

**On the synthetic adversaries.** The sharpest objection to this project
is that the detector finds imitations its own author generated. That
objection is correct, and it is why the technique breakdown on The Trust
Graph exists: the tactics are known by construction, so the honest thing
is to report which ones the detector handles well and which it does not.
Under no circumstances does this application display a real, named
organisation in a flagged or suspicious state. That is enforced in SQL,
not by convention, and an acceptance check fails the build if it is ever
violated.
        """
    )

    C.provenance_footer(
        "Batch identifier counts across every table, computed live so this "
        "tab cannot drift from reality."
    )
